02-modal
js-tasks-ru/htmlcss-20240216_y-dudar pull request #13
Opened 2024-03-15 16:58 UTC by KMS56135

2024-03-15 16:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-15 20:00 UTC, GSemikozov requested changes

2024-03-15 20:00 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    content: "";
content: ""; не надо

2024-03-15 22:19 UTC, KMS56135 commented on 05-lection3/02-modal/modal.css
> +    content: "";
Исправлено

2024-03-18 15:26 UTC, GSemikozov approved these changes

2024-03-18 15:27 UTC, merged