solution for  02-accordion
js-tasks-ru/htmlcss-20240216_y-dudar pull request #5
Opened 2024-02-28 19:01 UTC by KMS56135

2024-02-28 19:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-04 14:16 UTC, GSemikozov requested changes

2024-03-04 14:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 579px;
лучше max-width

2024-03-04 14:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 32px 32px;
снизу 32 только если .accordion__item[open] :)

2024-03-04 14:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    height: 72px;
не нужно

2024-03-04 14:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    height: 168px;
и тут

2024-03-04 14:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-top: 18px;
16

2024-03-04 16:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-05 22:13 UTC, GSemikozov requested changes

2024-03-05 22:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    line-height: 150%;
про font-family не забываем

2024-03-12 14:21 UTC, GSemikozov approved these changes

2024-03-12 14:21 UTC, merged