add font
js-tasks-ru/htmlcss-20240216_y-dudar pull request #9
Opened 2024-03-08 14:02 UTC by KMS56135

2024-03-08 14:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-09 11:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-09 11:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-12 14:23 UTC, GSemikozov requested changes

2024-03-12 14:23 UTC, GSemikozov commented on assets/css/main.css
>      --font-inter: "Inter", sans-serif;
тогда это --primary-family?

2024-03-12 14:25 UTC, merged